/// Flutter icons CustomIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Modern Pictograms, Copyright (c) 2012 by John Caserta. All rights reserved.
///         Author:    John Caserta
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://thedesignoffice.org/project/modern-pictograms/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Web Symbols, Copyright (c) 2011 by Just Be Nice studio. All rights reserved.
///         Author:    Just Be Nice studio
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.justbenicestudio.com/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';

  static const IconData flow_split = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData help_circled = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData card_giftcard = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData hotel = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData landscape = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData local_atm = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData music_note = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData record_voice_over = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData weekend = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData credit_card = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cloud_sun = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData sun_filled = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData dollar = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData na = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData photo = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData food = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData diamond = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData t_shirt = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData shop = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData archive = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData drop = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData lighter = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData poop = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData tools = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData healing = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData battery = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData picture_1 = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData book = const IconData(0xe828, fontFamily: _kFontFam);
  static const IconData pharmacy = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData religious_christian = const IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData tree_1 = const IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData gift = const IconData(0xe844, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xf0d6, fontFamily: _kFontFam);
  static const IconData youtube_play = const IconData(0xf16a, fontFamily: _kFontFam);
  static const IconData skype = const IconData(0xf17e, fontFamily: _kFontFam);
  static const IconData steam_squared = const IconData(0xf1b7, fontFamily: _kFontFam);
  static const IconData spotify = const IconData(0xf1bc, fontFamily: _kFontFam);
  static const IconData soundcloud = const IconData(0xf1be, fontFamily: _kFontFam);
  static const IconData soccer_ball = const IconData(0xf1e3, fontFamily: _kFontFam);
  static const IconData gwallet = const IconData(0xf1ee, fontFamily: _kFontFam);
  static const IconData cc_visa = const IconData(0xf1f0, fontFamily: _kFontFam);
  static const IconData cc_mastercard = const IconData(0xf1f1, fontFamily: _kFontFam);
  static const IconData cc_discover = const IconData(0xf1f2, fontFamily: _kFontFam);
  static const IconData cc_amex = const IconData(0xf1f3, fontFamily: _kFontFam);
  static const IconData cc_paypal = const IconData(0xf1f4, fontFamily: _kFontFam);
  static const IconData cc_stripe = const IconData(0xf1f5, fontFamily: _kFontFam);
  static const IconData chart_area = const IconData(0xf1fe, fontFamily: _kFontFam);
  static const IconData facebook_official = const IconData(0xf230, fontFamily: _kFontFam);
  static const IconData internet_explorer = const IconData(0xf26b, fontFamily: _kFontFam);
  static const IconData amazon = const IconData(0xf270, fontFamily: _kFontFam);
  static const IconData shopping_bag = const IconData(0xf290, fontFamily: _kFontFam);
  static const IconData shopping_basket = const IconData(0xf291, fontFamily: _kFontFam);
}